package cis44project;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.*;
import java.util.Collections;
import java.util.Arrays;

import java.awt.*;
import java.awt.event.*;
/**
 *
 * @author HERO
 */
public class StockGUI extends javax.swing.JFrame {
    FullStockList fullStockList;
   
    StockQueue stockQueue;
    //Stock stock;

    /**
     * Creates new form StockGUI
     */
    public StockGUI() {
        fullStockList = new FullStockList();
    
        initComponents();
        
        // Sync Stock Scrollbars in tandem
        BoundedRangeModel marriageTickerShares = tickerScrollPanel.getVerticalScrollBar().getModel();
        BoundedRangeModel marriageTickerEquity = tickerScrollPanel.getVerticalScrollBar().getModel();
        sharesScrollPanel.getVerticalScrollBar().setModel(marriageTickerShares);
        equityScrollPanel.getVerticalScrollBar().setModel(marriageTickerEquity);

        // Sync Watchlist Scrollbars in tandem
        //BoundedRangeModel marriageTickerWatchListPrice = WatchlistScrollPanel.getVerticalScrollBar().getModel();
       // priceWatchlistScrollPanel.getVerticalScrollBar().setModel(marriageTickerWatchListPrice);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        sortTickerButtonAsc = new javax.swing.JButton();
        sortSharesButtonAsc = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        tickerScrollPanel = new javax.swing.JScrollPane();
        tickerList = new javax.swing.JTextArea();
        sharesScrollPanel = new javax.swing.JScrollPane();
        sharesList = new javax.swing.JTextArea();
        sortTickerButtonDesc = new javax.swing.JButton();
        sortSharesButtonDesc = new javax.swing.JButton();
        equityScrollPanel = new javax.swing.JScrollPane();
        equityList = new javax.swing.JTextArea();
        sortEquityButtonAsc = new javax.swing.JButton();
        sortEquityButtonDesc = new javax.swing.JButton();
        stocksLabel = new javax.swing.JLabel();
        stocksPortfolioLabel = new javax.swing.JLabel();
        displayTotalEquityButton = new javax.swing.JButton();
        WatchlistLabel = new javax.swing.JLabel();
        displayTotalEquityScrollPanel = new javax.swing.JScrollPane();
        displayTotalEquity = new javax.swing.JTextPane();
        TickerLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        addWatchListButton = new javax.swing.JButton();
        StockNameLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTickerList = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPriceList = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(new java.awt.Color(0, 0, 0));

        sortTickerButtonAsc.setText("Sort Ticker [Ascending]");
        sortTickerButtonAsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortTickerButtonAscActionPerformed(evt);
            }
        });

        sortSharesButtonAsc.setText("Sort Shares [Ascending]");
        sortSharesButtonAsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortSharesButtonAscActionPerformed(evt);
            }
        });

        clearButton.setText("Sell All Stocks");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        tickerScrollPanel.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        tickerScrollPanel.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        tickerScrollPanel.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tickerScrollPanelPropertyChange(evt);
            }
        });

        tickerList.setColumns(20);
        tickerList.setRows(5);
        tickerList.setText(fullStockList.getStockTickers());
        tickerScrollPanel.setViewportView(tickerList);

        sharesScrollPanel.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        sharesScrollPanel.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                sharesScrollPanelPropertyChange(evt);
            }
        });

        sharesList.setColumns(20);
        sharesList.setRows(5);
        sharesList.setText(fullStockList.getShares());
        sharesScrollPanel.setViewportView(sharesList);

        sortTickerButtonDesc.setText("Sort Ticker [Descending]");
        sortTickerButtonDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortTickerButtonDescActionPerformed(evt);
            }
        });

        sortSharesButtonDesc.setText("Sort Shares [Descending]");
        sortSharesButtonDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortSharesButtonDescActionPerformed(evt);
            }
        });

        equityScrollPanel.setToolTipText("");
        equityScrollPanel.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        equityList.setColumns(20);
        equityList.setRows(5);
        equityList.setText(fullStockList.getEquity());
        equityScrollPanel.setViewportView(equityList);

        sortEquityButtonAsc.setText("Sort Equity [Ascending]");
        sortEquityButtonAsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortEquityButtonAscActionPerformed(evt);
            }
        });

        sortEquityButtonDesc.setText("Sort Equity [Descending]");
        sortEquityButtonDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortEquityButtonDescActionPerformed(evt);
            }
        });

        stocksLabel.setText("Stocks");

        stocksPortfolioLabel.setText("My Portfolio");

        displayTotalEquityButton.setText("Display Total Equity");
        displayTotalEquityButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayTotalEquityButtonActionPerformed(evt);
            }
        });

        WatchlistLabel.setText("Watchlist");

        displayTotalEquityScrollPanel.setViewportView(displayTotalEquity);

        TickerLabel.setText("Ticker");

        priceLabel.setText("Price (USD)");

        addWatchListButton.setText("Add");
        addWatchListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addWatchListButtonActionPerformed(evt);
            }
        });

        StockNameLabel.setText("Add to Stocks");

        jTickerList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "BABA",
                "BAC",
                "P" ,
                "GE" ,
                "F" ,
                "T" ,
                "SWN",
                "MDR",
                "ABEV",
                "NOK" ,
                "S" ,
                "TWTR" ,
                "TEVA",
                "VALE" ,
                "AKS" ,
                "PFE" ,
                "KKR",
                "WFC",
                "MRO" ,
                "PBR"  ,
                "TSLA"  ,
                "WFT"  ,
                "FCX"  ,
                "PE"  ,
                "FDC"  ,
                "JCP"  ,
                "RIG"  ,
                "KMI"  ,
                "ECA"  ,
                "FLR"  ,
                "AIG"  ,
                "C"  ,
                "ZAYO",
                "JPM"  ,
                "NWL"  ,
                "CVS"  ,
                "X"  ,
                "ITUB" ,
                "VER"  ,
                "WPX"  ,
                "DNR"  ,
                "MS"  ,
                "ORCL" ,
                "VZ"  ,
                "SQ"  ,
                "KO"  ,
                "CLF"  ,
                "BW"  ,
                "OAS"  ,
                "NLY"  ,
                "NRG"  ,
                "DIS"  ,
                "XOM"  ,
                "TSM"  ,
                "AUY"  ,
                "APRN"  ,
                "RF"  ,
                "VST"  ,
                "SYY"  ,
                "CBS"  ,
                "KGC"  ,
                "MGM"  ,
                "HBI"  ,
                "CNP"  ,
                "NBR"  ,
                "ESV"  ,
                "PG"  ,
                "CTL"  ,
                "MRK"  ,
                "MET"  ,
                "CX"  ,
                "CX"  ,
                "DWDP" ,
                "CAH"  ,
                "IBN"  ,
                "HST"  ,
                "JNPR"  ,
                "KEY"  ,
                "WMT"  ,
                "SHAK"  ,
                "M"  ,
                "CRC" ,
                "WMB"  ,
                "BWP"  ,
                "MO"  ,
                "GM"  ,
                "HP"  ,
                "HPQ" ,
                "VIPS" ,
                "DVN"  ,
                "ABX"  ,
                "HAL"  ,
                "KR"  ,
                "CPE"  ,
                "NFX"  ,
                "GIS"  ,
                "COP"  ,
                "HPE"  ,
                "BMY"  ,
                "USB"  ,
                "JNJ"  ,
                "NFLX"};
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jTickerList);

        jPriceList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] prices = { "188.89",
                "29.30",
                "6.89",
                "14.10",
                "10.79",
                "11.36",
                "3.05",
                "32.14",
                "4.03",
                "6.66",
                "6.33",
                "6.10",
                "5.28",
                "31.04",
                "17.83",
                "14.08",
                "4.53",
                "34.84",
                "23.00",
                "52.41",
                "19.72",
                "13.69",
                "301.06",
                "2.97",
                "15.42",
                "31.92",
                "19.08",
                "2.89",
                "12.08",
                "16.11",
                "13.16",
                "45.76",
                "52.84",
                "67.94",
                "32.97",
                "108.43",
                "27.65",
                "63.10",
                "34.52",
                "13.44",
                "6.94",
                "17.78",
                "3.40",
                "51.40",
                "45.71",
                "48.19",
                "49.10",
                "42.36",
                "7.69",
                "2.65",
                "11.22",
                "10.35",
                "33.30",
                "101.15",
                "76.90",
                "38.59",
                "2.93",
                "2.44",
                "18.72",
                "23.01",
                "62.29",
                "53.17",
                "4.03",
                "31.86",
                "16.81",
                "26.39",
                "7.54",
                "5.81",
                "72.43",
                "18.49",
                "57.75",
                "46.23",
                "5.96",
                "64.47",
                "53.01",
                "8.47",
                "19.84",
                "25.66",
                "19.70",
                "87.53",
                "55.95",
                "31.24",
                "31.58",
                "26.19",
                "9.56",
                "56.26",
                "36.71",
                "21.68",
                "15.75",
                "37.87",
                "13.47",
                "52.19",
                "24.14",
                "13.55",
                "27.34",
                "42.54",
                "66.86",
                "17.21",
                "51.33",
                "50.34",
                "124.19",
                "326.46"};
            public int getSize() { return prices.length; }
            public String getElementAt(int i) { return prices[i]; }
        });
        jScrollPane3.setViewportView(jPriceList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(stocksPortfolioLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(displayTotalEquityScrollPanel)
                            .addComponent(displayTotalEquityButton, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(49, 49, 49)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(clearButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(sortTickerButtonAsc, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(sortTickerButtonDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tickerScrollPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(sortSharesButtonDesc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(sharesScrollPanel, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(sortSharesButtonAsc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(sortEquityButtonDesc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(equityScrollPanel, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(sortEquityButtonAsc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(stocksLabel)
                                .addComponent(WatchlistLabel))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(TickerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(141, 141, 141))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(priceLabel)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addWatchListButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(StockNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stocksPortfolioLabel)
                .addGap(18, 18, 18)
                .addComponent(displayTotalEquityScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(displayTotalEquityButton)
                .addGap(19, 19, 19)
                .addComponent(stocksLabel)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sortTickerButtonAsc)
                    .addComponent(sortSharesButtonAsc)
                    .addComponent(sortEquityButtonAsc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sortEquityButtonDesc, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sortTickerButtonDesc)
                        .addComponent(sortSharesButtonDesc)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(sharesScrollPanel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tickerScrollPanel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(equityScrollPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clearButton)
                .addGap(18, 18, 18)
                .addComponent(WatchlistLabel)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TickerLabel)
                            .addComponent(priceLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(StockNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addWatchListButton))))
        );

        pack();
    }// </editor-fold>                        

    private void sortTickerButtonDescActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        fullStockList.sortByTickerDescending();
        tickerList.setText(fullStockList.getStockTickers());
        sharesList.setText(fullStockList.getShares());
        equityList.setText(fullStockList.getEquity());
    }                                                    

    private void sharesScrollPanelPropertyChange(java.beans.PropertyChangeEvent evt) {                                                 
        // TODO add your handling code here:
    }                                                

    private void tickerScrollPanelPropertyChange(java.beans.PropertyChangeEvent evt) {                                                 
        // Sync Stock Scrollbars in tandem

    }                                                

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // clear text
        tickerList.setText("");
        sharesList.setText("");
        equityList.setText("");
    }                                           

    private void sortSharesButtonAscActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        fullStockList.sortByShares();
        tickerList.setText(fullStockList.getStockTickers());
        sharesList.setText(fullStockList.getShares());
        equityList.setText(fullStockList.getEquity());
    }                                                   

    private void sortTickerButtonAscActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        fullStockList.sortByTicker();
        tickerList.setText(fullStockList.getStockTickers());
        sharesList.setText(fullStockList.getShares());
        equityList.setText(fullStockList.getEquity());
    }                                                   

    private void displayTotalEquityButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                         
        displayTotalEquity.setText(fullStockList.getTotalEquity());
    }                                                        

    private void sortEquityButtonDescActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        fullStockList.sortByEquityDescending();
        tickerList.setText(fullStockList.getStockTickers());
        sharesList.setText(fullStockList.getShares());
        equityList.setText(fullStockList.getEquity());
    }                                                    

    private void sortEquityButtonAscActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        fullStockList.sortByEquity();
        tickerList.setText(fullStockList.getStockTickers());
        sharesList.setText(fullStockList.getShares());
        equityList.setText(fullStockList.getEquity());
    }                                                   

    private void sortSharesButtonDescActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        fullStockList.sortBySharesDescending();
        tickerList.setText(fullStockList.getStockTickers());
        sharesList.setText(fullStockList.getShares());
        equityList.setText(fullStockList.getEquity());
    }                                                    

    private void addWatchListButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                   

    }                                                  

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StockGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StockGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StockGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StockGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StockGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel StockNameLabel;
    private javax.swing.JLabel TickerLabel;
    private javax.swing.JLabel WatchlistLabel;
    private javax.swing.JButton addWatchListButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JTextPane displayTotalEquity;
    private javax.swing.JButton displayTotalEquityButton;
    private javax.swing.JScrollPane displayTotalEquityScrollPanel;
    private javax.swing.JTextArea equityList;
    private javax.swing.JScrollPane equityScrollPanel;
    private javax.swing.JList<String> jPriceList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> jTickerList;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JTextArea sharesList;
    private javax.swing.JScrollPane sharesScrollPanel;
    private javax.swing.JButton sortEquityButtonAsc;
    private javax.swing.JButton sortEquityButtonDesc;
    private javax.swing.JButton sortSharesButtonAsc;
    private javax.swing.JButton sortSharesButtonDesc;
    private javax.swing.JButton sortTickerButtonAsc;
    private javax.swing.JButton sortTickerButtonDesc;
    private javax.swing.JLabel stocksLabel;
    private javax.swing.JLabel stocksPortfolioLabel;
    private javax.swing.JTextArea tickerList;
    private javax.swing.JScrollPane tickerScrollPanel;
    // End of variables declaration                   
}
